test_init =   [
		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		]

scen2 =   [
		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		{
		'position_x':0.0,
		'position_y':0.0,
		'type':'grass',
		'state':'alive',
		'age':0.0,
		'max_age':20.0,
		'age_rate':0.1,
		'food':5.0,
		'reproduce_food':100.0,
		'max_speed':5.0,
		'behaviour':'Avoid',
		},

		]
